import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {signIn, useSession} from 'next-auth/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data:session}:any = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {session && <div className={styles.container}>
        <div>
          <h1>{session.user}</h1>
        </div>
      </div>
     }

{!session && <div className={styles.container}>
  <button onClick={() => signIn()}>Sign in</button>
</div>
}
    </>
  )
}
